#include QMK_KEYBOARD_H
#include "version.h"
#include "keymap_swedish.h"

enum planck_layers {
  _BASE,
  _LOWER,
  _RAISE,
  _ADJUST,
  _LAYER4,
  _LAYER5,
};

#define LOWER MO(_LOWER)
#define RAISE MO(_RAISE)
#define ADJUST MO(_ADJUST)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_BASE] = LAYOUT(KC_ESCAPE,KC_Q,KC_W,KC_E,KC_R,KC_T,KC_Y,KC_U,KC_I,KC_O,KC_P,KC_BSPACE,KC_TAB,KC_A,KC_S,KC_D,LT(4,KC_F),KC_G,KC_H,KC_J,KC_K,KC_L,SE_SCLN,SE_APOS,LT(5,KC_NO),KC_Z,KC_X,KC_C,KC_V,KC_B,KC_N,KC_M,KC_COMMA,KC_DOT,SE_SLSH,KC_ENTER,LT(4,KC_NO),KC_LCTRL,KC_LALT,KC_LGUI,RAISE,KC_SPACE,KC_NO,LOWER,KC_LEFT,KC_RIGHT,KC_DOWN,KC_UP),
  [_LOWER] = LAYOUT(SE_TILD,KC_EXLM,SE_AT,KC_HASH,SE_DLR,KC_PERC,SE_CIRC,SE_AMPR,SE_ASTR,SE_LPRN,SE_RPRN,SE_MINS,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,SE_LBRC,SE_RBRC,KC_TRANSPARENT,KC_TRANSPARENT,SE_LPRN,SE_RPRN,SE_PIPE_MAC,KC_TRANSPARENT,SE_UNDS,KC_LSHIFT,KC_TRANSPARENT,KC_TRANSPARENT,SE_LCBR_MAC,SE_RCBR_MAC,KC_TRANSPARENT,KC_TRANSPARENT,SE_PLUS,SE_EQL,SE_BSLS_MAC,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,MO(2),KC_TRANSPARENT,KC_NO,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),
  [_RAISE] = LAYOUT(SE_ACUT,KC_1,KC_2,KC_3,KC_4,KC_5,KC_6,KC_7,KC_8,KC_9,KC_0,SE_AA,KC_TRANSPARENT,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_TRANSPARENT,KC_4,KC_5,KC_6,SE_OSLH,SE_ADIA,KC_LSHIFT,KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,KC_TRANSPARENT,KC_1,KC_2,KC_3,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,KC_0,KC_DOT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),
  [_ADJUST] = LAYOUT(RESET,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,RGB_SPD,KC_TRANSPARENT,KC_TRANSPARENT,KC_SYSTEM_SLEEP,KC_ASTG,KC_ASDN,KC_ASUP,KC_ASRP,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,RGB_TOG,RGB_VAD,RGB_VAI,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_AUDIO_MUTE,KC_AUDIO_VOL_DOWN,KC_AUDIO_VOL_UP,KC_NO,RGB_MOD,RGB_HUD,RGB_HUI,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),
  [_LAYER4] = LAYOUT(KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LCTL(LGUI(KC_LEFT)),KC_UP,LCTL(LGUI(KC_RIGHT)),KC_TRANSPARENT,KC_DELETE,KC_TRANSPARENT,KC_LGUI,KC_LALT,KC_LSHIFT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_LEFT,KC_DOWN,KC_RIGHT,KC_TRANSPARENT,KC_TRANSPARENT,KC_LSHIFT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,LGUI(KC_0),LGUI(LSFT(KC_Y)),LALT(LGUI(KC_0)),KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),
  [_LAYER5] = LAYOUT(KC_LSHIFT,LSFT(KC_Q),LSFT(KC_W),LSFT(KC_E),LSFT(KC_R),LSFT(KC_T),LSFT(KC_Y),LSFT(KC_U),LSFT(KC_I),LSFT(KC_O),LSFT(KC_P),KC_TRANSPARENT,LSFT(KC_TAB),LSFT(KC_A),LSFT(KC_S),LSFT(KC_D),LSFT(KC_F),LSFT(KC_G),LSFT(KC_H),LSFT(KC_J),LSFT(KC_K),LSFT(KC_L),SE_COLN,SE_DQUO,KC_TRANSPARENT,LSFT(KC_Z),LSFT(KC_X),LSFT(KC_C),LSFT(KC_V),LSFT(KC_B),LSFT(KC_N),LSFT(KC_M),SE_LESS_MAC,SE_GRTR_MAC,SE_QUES,LSFT(KC_ENTER),KC_TRANSPARENT,LSFT(KC_LCTRL),LSFT(KC_LALT),LSFT(KC_LGUI),KC_TRANSPARENT,KC_TRANSPARENT,KC_NO,KC_TRANSPARENT,LSFT(KC_LEFT),LSFT(KC_RIGHT),LSFT(KC_DOWN),LSFT(KC_UP)),
};
