#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		MO(2),			KC_BSPC,	KC_UP,		KC_DEL,
		XXXXXXX,		KC_LEFT,	KC_DOWN,	KC_RGHT,
		MO(3),			KC_SPC,		KC_TAB,		KC_ENT,
		KC_LSFT,		KC_LCTL,	KC_LALT,	KC_LGUI),
	[1] = LAYOUT(
		LT(2,KC_PSLS),	KC_P7,		KC_P8,		KC_P9,
		KC_PAST,		KC_P4,		KC_P5,		KC_P6,
		KC_PMNS,		KC_P1,		KC_P2,		KC_P3,
		KC_PPLS,		KC_P0,		KC_PDOT,	KC_PENT),
	[2]=LAYOUT(
		_______,		DF(0),		DF(1),		RESET,
		KC_D,			KC_X,		KC_K,		KC_S,
		KC_LSHIFT,		KC_RSHIFT,	XXXXXXX,	XXXXXXX,
		XXXXXXX,		XXXXXXX,	XXXXXXX,	XXXXXXX),
	[3]=LAYOUT(
		XXXXXXX,		G(KC_Z),	S(G(KC_Z)),	XXXXXXX,
		XXXXXXX,		G(KC_C),	G(KC_V),	G(KC_X),
		_______,		XXXXXXX,	XXXXXXX,	XXXXXXX,
		XXXXXXX,		XXXXXXX,	XXXXXXX,	XXXXXXX)
};
