#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		LT(2,KC_NO), KC_BSPC, KC_UP, KC_DEL, 
		KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, 
		LT(3,KC_NO), KC_SPC, KC_TAB, KC_ENT, 
		KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI),
	[1] = LAYOUT(
		LT(2,KC_P7), KC_P8, KC_P9, KC_PSLS, 
		KC_P4, KC_P5, KC_P6, KC_PAST, 
		KC_P1, KC_P2, KC_P3, KC_PMNS, 
		KC_P0, KC_PDOT, KC_PENT, KC_PPLS),
	[2] = LAYOUT(
		KC_TRNS, DF(0), DF(1), RESET,
		KC_D, KC_X, KC_K, KC_S, 
		KC_LSHIFT, KC_RSHIFT, KC_NO, KC_NO, 
		KC_NO, KC_NO, KC_NO, KC_NO),
	[3] = LAYOUT(
		KC_NO, LGUI(KC_Z), LSFT(LGUI(KC_Z)), KC_NO,
		KC_NO, LGUI(KC_C), LGUI(KC_V), LGUI(KC_X), 
		KC_TRNS, KC_NO, KC_NO, KC_NO, 
		KC_NO, KC_NO, KC_NO, KC_NO)
};
